version: "3.8"

services:
 app:
  build: .
  ports:
   - "3000:3000"
  environment:
   - MONGODB_URL="mongodb://mongodb:27017"
   - PAYLOAD_SECRET=${PAYLOAD_SECRET}
   - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
   - RESEND_API_KEY=${RESEND_API_KEY}
   - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
   - STRIPE_WEBHOOK_KEY=${STRIPE_WEBHOOK_KEY}
  depends_on:
   - mongodb

 mongodb:
  image: mongo:latest
  container_name: mongodb
  ports:
   - "27017:27017"
