name: CD

on:
 workflow_dispatch:
 push:
  branches: ["production"]

jobs:
 build:
  runs-on: self-hosted

  steps:
   - name: Checkout
     uses: actions/checkout@v3
   - name: Run docker container
     env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
      NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_KEY: ${{ secrets.STRIPE_WEBHOOK_KEY }}
     run: docker compose up --build -d --force-recreate
